version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres-local
      DB_PASSWORD: postgres
      DB_DATABASE: postgres-local
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres-local
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
